### PR TITLE
get event loop for aws_channel

### PR DESCRIPTION
**Pull request by bretambrose**
Adds get accessor to go from channel (hidden impl) to the owning event loop.  Needed in order to cancel tasks from a channel handler.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by JonathanHenson** [comment]
There’s already a channel cancel task api. Is this because the reconnect task is not on the channel? If so why not just grab an event loop off of the eventloop group directly?

**Comment by JonathanHenson** [comment]
Yeah I’m now confused why you need this at all. You already have the event loop group

**Comment by bretambrose** [comment]
> 
> 
> There’s already a channel cancel task api. Is this because the reconnect task is not on the channel? If so why not just grab an event loop off of the eventloop group directly?

I did not see cancel task channel/handler/slot api.

**Comment by bretambrose** [comment]
Closing and renaming to match downstream branch name

**Pull request closed without merging**
