### PR TITLE
Use const pointers in `secure_channel_tls_handler.c`.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
*Issue #, if available:*

*Description of changes:*

This PR uses `PCCERT_***` types in two cases, which are aliases for const pointers.

Fixes build failures on MinGW.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by waahm7** [comment]
Unfortunately, at the moment we don't support MinGW. What is your use-case? Is this the only problem you are facing with MinGW, or is this just the first of N problems?

**Comment by teo-tsirpanis** [comment]
I discovered this while working updating dependencies (TileDB-Inc/TileDB#5010), and after applying this patch `aws-c-io` builds in MinGW[^1]. Before making the patch, I tried to build without this warning and without any warnings, but for some reason this warning could not be suppressed and always escalated to an error.

I think this change is good regardless of the MinGW situation, because it matches the constness of the pointers with the API signatures ([example 1](https://learn.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-certfreecertificatecontext), [example 2](https://learn.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-certgetcertificatechain)).

[^1]: There was another error in `aws-sdk-cpp` which needs more thought on if and how to fix upstream.

**Comment by waahm7** [comment]
Thanks, LGTM!

**Comment by waahm7** [comment]
Released in https://github.com/awslabs/aws-c-io/releases/tag/v0.14.16.

**Pull request merged**
